import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Eye, Calendar, Clock } from "lucide-react";

export const ExamplesSection = () => {
  const examples = [
    {
      title: "10 Essential CRM Features Every SaaS Company Needs in 2024",
      excerpt: "Discover the must-have CRM features that top SaaS companies use to increase customer retention by 40% and boost revenue...",
      category: "SaaS",
      readTime: "8 min read",
      publishDate: "Published 2 days ago",
      image: "/api/placeholder/400/200"
    },
    {
      title: "How to Choose the Right E-commerce Platform: Shopify vs WooCommerce",
      excerpt: "A comprehensive comparison of the two leading e-commerce platforms, including costs, features, and which one fits your business best...",
      category: "E-commerce", 
      readTime: "12 min read",
      publishDate: "Published 5 days ago",
      image: "/api/placeholder/400/200"
    },
    {
      title: "Local SEO Checklist: 15 Steps to Dominate Your City's Search Results",
      excerpt: "The complete guide to local SEO that helped 200+ local businesses increase their Google My Business views by 300%...",
      category: "Local Business",
      readTime: "15 min read", 
      publishDate: "Published 1 week ago",
      image: "/api/placeholder/400/200"
    }
  ];

  return (
    <section className="py-20 px-4">
      <div className="container mx-auto max-w-6xl">
        <div className="text-center space-y-6 mb-16">
          <h2 className="text-4xl lg:text-5xl font-bold text-foreground">
            See what AIWU creates
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Real blog posts generated 100% by AIWU. These aren't templates — 
            each one is custom-written for the specific business.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {examples.map((example, index) => (
            <Card key={index} className="overflow-hidden hover:shadow-warm transition-all duration-200 bg-card border-border group">
              {/* Image placeholder */}
              <div className="h-48 bg-gradient-to-br from-orange-100 to-orange-50 flex items-center justify-center">
                <div className="text-center space-y-2">
                  <div className="w-16 h-16 mx-auto bg-white rounded-lg flex items-center justify-center shadow-soft">
                    <Eye className="w-8 h-8 text-primary" />
                  </div>
                  <p className="text-sm text-muted-foreground">Article Preview</p>
                </div>
              </div>

              <div className="p-6 space-y-4">
                {/* Category and meta */}
                <div className="flex items-center justify-between">
                  <Badge variant="secondary" className="bg-orange-100 text-primary border-orange-200">
                    {example.category}
                  </Badge>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <Clock className="w-3 h-3" />
                    {example.readTime}
                  </div>
                </div>

                {/* Title */}
                <h3 className="text-xl font-semibold text-foreground leading-tight group-hover:text-primary transition-colors">
                  {example.title}
                </h3>

                {/* Excerpt */}
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {example.excerpt}
                </p>

                {/* Meta info */}
                <div className="flex items-center justify-between pt-2 border-t border-border">
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <Calendar className="w-3 h-3" />
                    {example.publishDate}
                  </div>
                  <Badge className="bg-primary text-white text-xs">
                    Generated by AIWU
                  </Badge>
                </div>
              </div>
            </Card>
          ))}
        </div>

        <div className="mt-16 text-center space-y-6">
          <p className="text-lg text-muted-foreground">
            Each article includes tables, images, CTAs, and internal links — 
            everything you need to rank and convert.
          </p>

          <div className="inline-block p-6 bg-orange-50 rounded-lg border border-orange-100">
            <p className="font-medium text-foreground mb-1">
              These articles rank on page 1 of Google
            </p>
            <p className="text-sm text-muted-foreground">
              Average ranking position: #4 within 60 days
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};